version: "3.8"

services:
  backend:
    build: .
    image: bms-backend:latest
    container_name: bms-backend-container
    env_file:
      - .env
    ports:
      - "4000:4000"
    restart: always
